# Generated by Django 5.2.8 on 2025-11-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_cards', models.CharField(max_length=50)),
                ('flop', models.CharField(max_length=50)),
                ('turn', models.CharField(max_length=10)),
                ('river', models.CharField(max_length=10)),
                ('best_hand', models.CharField(max_length=50)),
                ('hand_rank', models.IntegerField()),
                ('evaluation_log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
