# Generated by Django 5.2.8 on 2025-11-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent_cards',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='outcome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
