# Generated by Django 5.2.8 on 2025-11-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_opponent_cards_game_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='outcome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
